# Generated by Django 3.0.5 on 2020-04-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200407_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Submitted'), ('C', 'Complete')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
