# Generated by Django 3.0.5 on 2020-04-08 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200407_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 4, 34, 14, 755149, tzinfo=utc)),
        ),
    ]
