# Generated by Django 3.0.5 on 2020-04-09 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200409_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(default='AR', on_delete=django.db.models.deletion.CASCADE, to='orders.State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 6, 33, 56, 779751, tzinfo=utc)),
        ),
    ]
