# Generated by Django 3.0.5 on 2020-04-09 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200409_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 6, 36, 20, 416058, tzinfo=utc)),
        ),
    ]
