# Generated by Django 3.0.5 on 2020-04-09 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200409_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='AR', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 6, 37, 58, 608092, tzinfo=utc)),
        ),
    ]
