# Generated by Django 3.0.5 on 2020-04-09 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200409_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 7, 17, 55, 95663, tzinfo=utc)),
        ),
    ]
