# Generated by Django 3.0.5 on 2020-04-23 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200409_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 3, 33, 27, 662023, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Pizza_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='static/orders')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza_Style')),
            ],
        ),
    ]
