# Generated by Django 3.0.5 on 2020-04-23 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200422_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 3, 57, 22, 713110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pizza_pic',
            name='pic',
            field=models.ImageField(upload_to='orders/static/orders'),
        ),
    ]
