# Generated by Django 3.0.5 on 2020-04-23 04:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200422_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 4, 13, 30, 567294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pizza_pic',
            name='pic',
            field=models.ImageField(upload_to='static/orders'),
        ),
    ]
