# Generated by Django 3.0.5 on 2020-04-30 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200429_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_style',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 4, 31, 18, 30294, tzinfo=utc)),
        ),
    ]
